"""
03 — Multi-Agent Orchestration

Shows how to build an orchestrator that delegates work to sub-agents:
  - Define specialized sub-agents (researcher, writer)
  - Register them with the orchestrator
  - Stream events including subagent.started / subagent.completed

No database required — uses in-memory persistence.
"""

import asyncio

from fg_agents import (
    AgentDefinition,
    AgentLLM,
    Orchestrator,
    ToolRegistry,
    create_repository,
    tool,
)


# --- Tools for the researcher sub-agent ------------------------------------
@tool(description="Search the web for information on a topic")
async def search_web(query: str) -> str:
    # In production, call a real search API here
    return f"[Search results for '{query}']: Found 3 relevant articles about {query}."


@tool(description="Extract key facts from search results")
def extract_facts(text: str) -> str:
    return f"Key facts extracted: {text[:80]}..."


# --- Tools for the writer sub-agent ---------------------------------------
@tool(description="Write a structured summary from provided facts")
def write_summary(topic: str, facts: str) -> str:
    return f"# Summary: {topic}\n\n{facts}\n\n---\nGenerated by Fareground Writer Agent."


# --- Build the orchestrator -----------------------------------------------
async def main():
    llm = AgentLLM()
    repo = create_repository("memory")
    await repo.initialize()

    # Main tool registry (for the brain agent's built-in tools)
    main_tools = ToolRegistry()

    # Register all tools — the orchestrator routes them to the right sub-agent
    main_tools.register_many([search_web, extract_facts, write_summary])

    # Sub-agent definitions
    researcher = AgentDefinition(
        name="researcher",
        model="ollama:qwen3:8b",
        system_prompt=(
            "You are a research assistant. Use search_web to find information, "
            "then extract_facts to distill key points. Return the facts."
        ),
        tools=["search_web", "extract_facts"],
    )

    writer = AgentDefinition(
        name="writer",
        model="ollama:qwen3:8b",
        system_prompt=(
            "You are a technical writer. Take the facts provided and use "
            "write_summary to create a clear, structured summary."
        ),
        tools=["write_summary"],
    )

    # Brain agent orchestrates the two sub-agents
    brain = AgentDefinition(
        name="brain",
        model="ollama:qwen3:8b",
        system_prompt=(
            "You coordinate research tasks. First delegate to the 'researcher' "
            "to gather facts, then delegate to the 'writer' to produce the final summary."
        ),
    )

    # Wire up the orchestrator
    orchestrator = Orchestrator(
        llm=llm,
        tool_registry=main_tools,
        repository=repo,
    )
    orchestrator.register_sub_agent("researcher", researcher)
    orchestrator.register_sub_agent("writer", writer)
    await orchestrator.initialize()

    # Stream all events, including sub-agent lifecycle
    async for event in orchestrator.run(
        "session-1",
        "Research and summarize the latest trends in AI agents.",
        brain,
    ):
        if event.type.value == "subagent.started":
            print(f"\n>>> Sub-agent started: {event.data['agent_name']}")
        elif event.type.value == "subagent.completed":
            print(f"<<< Sub-agent completed: {event.data['agent_name']}\n")
        elif event.data.get("text"):
            print(event.data["text"], end="", flush=True)
        elif event.type.value == "tool.result":
            print(f"  [tool] {event.data['tool_name']}: {event.data['status']}")
        elif event.type.value == "session.completed":
            print(f"\nDone in {event.data['total_turns']} turns")

    print()
    await orchestrator.shutdown()


if __name__ == "__main__":
    asyncio.run(main())
